minimumReleaseAge: 2880
minimumReleaseAgeExclude:
- '@ston-fi/*'

onlyBuiltDependencies:
- '@biomejs/biome'
- '@ston-fi/*'
- 'lefthook'

packages:
  - 'packages/*'
  - 'examples/*'

verifyDepsBeforeRun: 'install'

catalog:
  '@arethetypeswrong/cli': 0.18.2
  'publint': 0.3.15
  'vitest': 3.2.4
  'tsdown': 0.15.9
